# docker-compose config

version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=source_db
      - PGDATA=/data/postgres
    ports:
      - 5432:5432
    volumes:
      - ../data/raw/postgres:/var/lib/postgres/data
    
# volumes:
  # pgdata: